version: '3'
services:
  ktor-rest-app:
    image: "somedockercompany/simple-rest-app:latest"
    ports:
      - "8090:8080"
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
        max_attempts: 2
